### ISSUE TITLE
npm test issues

### ISSUE THREAD

**Issue by ghost** [appuri/mock-http-server#14]
Hi,

I am unable to run the test.
I followed the instructions.
Node is installed
Npm is solid
vows is installed
I researched it on a few sites

Much Thanks,
RW

C:_git\Automation\mock-http-server>npm test

> mock-http-server@1.0.0 test C:_git\Automation\mock-http-server
> rm -f test/fixtures/_.response && vows --spec test/_-test.coffee

C:_git\Automation\mock-http-server\test\mock-http-server-test.coffee:1
(function (exports, require, module, __filename, __dirname) { #
                                                               ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\eil\AppData\Roaming\npm\node_modules\vows\bin\vows:567:19
    at Array.reduce (native)
    at importSuites (C:\Users\eil\AppData\Roaming\npm\node_modules\vows\bin\vows
:560:18)
 npm ERR! Test failed.  See above for more details.

**Comment by ghost** [comment]
No response, gave up.
